// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOLsZc24dapzIHs9TttFTJF2TiBL-DDXo',
    appId: '1:1000423238353:web:270216c784e3837fb733f0',
    messagingSenderId: '1000423238353',
    projectId: 'volunteerapp-22dce',
    authDomain: 'volunteerapp-22dce.firebaseapp.com',
    databaseURL: 'https://volunteerapp-22dce-default-rtdb.firebaseio.com',
    storageBucket: 'volunteerapp-22dce.firebasestorage.app',
    measurementId: 'G-8QXQ9E08Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO_j7YukPQt45DneO-abdBRNHUPCNL8Xs',
    appId: '1:1000423238353:android:e143f61160bd6c4bb733f0',
    messagingSenderId: '1000423238353',
    projectId: 'volunteerapp-22dce',
    databaseURL: 'https://volunteerapp-22dce-default-rtdb.firebaseio.com',
    storageBucket: 'volunteerapp-22dce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPiq0MUcwhyw93dQN1inVgEuPhOmYckeg',
    appId: '1:1000423238353:ios:6df77e31f424b15ab733f0',
    messagingSenderId: '1000423238353',
    projectId: 'volunteerapp-22dce',
    databaseURL: 'https://volunteerapp-22dce-default-rtdb.firebaseio.com',
    storageBucket: 'volunteerapp-22dce.firebasestorage.app',
    androidClientId: '1000423238353-ve06016l8ej8ga7jq7onc9oomj6hb6r2.apps.googleusercontent.com',
    iosClientId: '1000423238353-k7rl6kpt5a0f7c5e8kumasmdr8hobs26.apps.googleusercontent.com',
    iosBundleId: 'com.example.ramizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPiq0MUcwhyw93dQN1inVgEuPhOmYckeg',
    appId: '1:1000423238353:ios:6df77e31f424b15ab733f0',
    messagingSenderId: '1000423238353',
    projectId: 'volunteerapp-22dce',
    databaseURL: 'https://volunteerapp-22dce-default-rtdb.firebaseio.com',
    storageBucket: 'volunteerapp-22dce.firebasestorage.app',
    androidClientId: '1000423238353-ve06016l8ej8ga7jq7onc9oomj6hb6r2.apps.googleusercontent.com',
    iosClientId: '1000423238353-k7rl6kpt5a0f7c5e8kumasmdr8hobs26.apps.googleusercontent.com',
    iosBundleId: 'com.example.ramizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOLsZc24dapzIHs9TttFTJF2TiBL-DDXo',
    appId: '1:1000423238353:web:8c5761feb0151415b733f0',
    messagingSenderId: '1000423238353',
    projectId: 'volunteerapp-22dce',
    authDomain: 'volunteerapp-22dce.firebaseapp.com',
    databaseURL: 'https://volunteerapp-22dce-default-rtdb.firebaseio.com',
    storageBucket: 'volunteerapp-22dce.firebasestorage.app',
    measurementId: 'G-FDLEW2RRX6',
  );

}